name: learn-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "Hello"
      - name: cache message
        run: echo "todo cache a message"
      - name: sleep for 5s
        run: sleep 5s
  temp-job-2:
    needs: echo-message
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "Hello job 2"
  temp-job-3:
    needs: echo-message
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "Hello job 3"
  cleanup-job:
    needs: [ temp-job-2, temp-job-3 ]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "Hello cleanup"
